name: NodeJS and Vue

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20.x']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Navigate to the backend directory
        run: cd pcollection/backend

      - name: Install Dependencies
        run: npm install

      - name: Run Jest tests with --detectOpenHandles
        run: npx jest --detectOpenHandles
